In [1]:
import tensorflow as tf

In [2]:
#tensorflow 안에서 grdient를 손대고 싶을 떄 사용하는 방법
X = [1, 2, 3]
Y = [1, 2, 3]

W = tf.Variable(5.)
hypothesis = X * W

#직접 구한 gradient값
gradient = tf.reduce_mean((W * X - Y) * X) * 2

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.01)

#Gradient값을 얻는다.
gvs = optimizer.compute_gradients(cost,[W])

#Gradient 적용
apply_gradient = optimizer.apply_gradients(gvs)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(100):
    print(step, sess.run([gradient,  gvs]))
    sess.run(apply_gradient)

0 [37.333332, [(37.333332, 5.0)]]
1 [33.848888, [(33.848888, 4.6266665)]]
2 [30.689655, [(30.689655, 4.2881775)]]
3 [27.825289, [(27.825289, 3.981281)]]
4 [25.228264, [(25.228264, 3.7030282)]]
5 [22.873627, [(22.873627, 3.4507456)]]
6 [20.738754, [(20.738754, 3.2220094)]]
7 [18.803141, [(18.803141, 3.014622)]]
8 [17.04818, [(17.048178, 2.8265905)]]
9 [15.457016, [(15.457016, 2.6561089)]]
10 [14.014363, [(14.014362, 2.5015388)]]
11 [12.706355, [(12.706355, 2.3613951)]]
12 [11.520428, [(11.520428, 2.2343316)]]
13 [10.445188, [(10.445188, 2.1191273)]]
14 [9.4703045, [(9.4703045, 2.0146754)]]
15 [8.5864086, [(8.5864077, 1.9199723)]]
16 [7.7850103, [(7.7850103, 1.8341082)]]
17 [7.0584097, [(7.0584097, 1.7562581)]]
18 [6.3996248, [(6.3996248, 1.6856741)]]
19 [5.8023272, [(5.8023272, 1.6216779)]]
20 [5.2607765, [(5.2607765, 1.5636547)]]
21 [4.7697711, [(4.7697711, 1.5110469)]]
22 [4.3245926, [(4.3245926, 1.4633492)]]
23 [3.9209647, [(3.9209647, 1.4201033)]]
24 [3.5550079, [(3.5550079, 1.38089

# Multi-variable linear regression
- hypothesis : H(X1,X2,X3....) = W1X1 + W2X2 + ...  WnXn
- cost : 


In [3]:
#5개의 샘플 데이터 
x1_data = [73, 93, 89, 96, 73]
x2_data = [80, 88, 91, 98, 66]
x3_data = [75, 93, 90, 100, 70]
y_data = [152, 185, 180, 196, 142]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = x1 * w1 + x2 * w2 + x3 + w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    if step % 10 == 0:
        print(step, "cost : ", cost_val, "\nprediction\n", hy_val)

0 cost :  7565.36 
prediction
 [ 224.28269958  280.31152344  270.62927246  294.78259277  216.47198486]
10 cost :  18.9448 
prediction
 [ 148.84657288  191.04753113  181.87133789  199.12184143  147.91265869]
20 cost :  11.1364 
prediction
 [ 146.43980408  188.17832947  179.02955627  196.05882263  145.70391846]
30 cost :  11.074 
prediction
 [ 146.37393188  188.07849121  178.94177246  195.96394348  145.62202454]
40 cost :  11.0199 
prediction
 [ 146.3830719   188.06745911  178.942276    195.96421814  145.60836792]
50 cost :  10.9661 
prediction
 [ 146.39456177  188.0592804   178.9455719   195.96751404  145.59689331]
60 cost :  10.9126 
prediction
 [ 146.40611267  188.05122375  178.94895935  195.97093201  145.58554077]
70 cost :  10.8594 
prediction
 [ 146.41763306  188.04318237  178.9523468   195.97431946  145.57420349]
80 cost :  10.8065 
prediction
 [ 146.42912292  188.03517151  178.95570374  195.97767639  145.56291199]
90 cost :  10.7538 
prediction
 [ 146.44059753  188.0271759   178.

820 cost :  7.56678 
prediction
 [ 147.20120239  187.49656677  179.18231201  196.20487976  144.80392456]
830 cost :  7.53104 
prediction
 [ 147.21066284  187.49000549  179.18510437  196.20767212  144.79466248]
840 cost :  7.49545 
prediction
 [ 147.22007751  187.4834137   179.18785095  196.21043396  144.78538513]
850 cost :  7.4601 
prediction
 [ 147.22946167  187.47686768  179.19061279  196.2131958   144.77615356]
860 cost :  7.42491 
prediction
 [ 147.23883057  187.47032166  179.19335938  196.21594238  144.76695251]
870 cost :  7.38989 
prediction
 [ 147.2481842   187.46380615  179.19610596  196.21870422  144.75776672]
880 cost :  7.35511 
prediction
 [ 147.25749207  187.45732117  179.19883728  196.22145081  144.74861145]
890 cost :  7.32045 
prediction
 [ 147.26678467  187.45082092  179.20155334  196.22416687  144.73945618]
900 cost :  7.28599 
prediction
 [ 147.27606201  187.4443512   179.20428467  196.22688293  144.73036194]
910 cost :  7.25172 
prediction
 [ 147.28529358  187.437

1630 cost :  5.20114 
prediction
 [ 147.89131165  187.0151825   179.3848114   196.40785217  144.1257019 ]
1640 cost :  5.17777 
prediction
 [ 147.89892578  187.00984192  179.38703918  196.41009521  144.11817932]
1650 cost :  5.1545 
prediction
 [ 147.90655518  187.00453186  179.38929749  196.41233826  144.11070251]
1660 cost :  5.13135 
prediction
 [ 147.91415405  186.99923706  179.39152527  196.41456604  144.10322571]
1670 cost :  5.10834 
prediction
 [ 147.92173767  186.99395752  179.39375305  196.41680908  144.09579468]
1680 cost :  5.08547 
prediction
 [ 147.92927551  186.98867798  179.39595032  196.41902161  144.08836365]
1690 cost :  5.06266 
prediction
 [ 147.93684387  186.98342896  179.3981781   196.42124939  144.08096313]
1700 cost :  5.04 
prediction
 [ 147.9443512   186.97817993  179.40037537  196.42344666  144.07356262]
1710 cost :  5.01745 
prediction
 [ 147.95185852  186.97294617  179.40260315  196.42567444  144.06620789]
1720 cost :  4.99506 
prediction
 [ 147.95932007  

# Multi-Variables linear regression by Matrix

In [4]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]
with tf.device('/cpu:0'):
    #Placeholder for tensor that will be always fed
    #None은 원하는 어떠한 값이든 넣을 수 있다는 뜻 
    X = tf.placeholder(tf.float32, shape=[None, 3])
    Y = tf.placeholder(tf.float32, shape=[None, 1])

    W = tf.Variable(tf.random_normal([3, 1], name = 'weight'))
    b = tf.Variable(tf.random_normal([1]), name = 'bias')
    #hypothesis and cost
    hypothesis = tf.matmul(X, W) + b
    cost = tf.reduce_mean(tf.square(hypothesis - Y))

    #minimize
    optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
    train = optimizer.minimize(cost)

#Launch the graph in a Session
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X : x_data, Y : y_data})
    if step % 10 == 0:
        print(step, "cost : ", cost_val, "\nPrediction :\n ", hy_val)

0 cost :  30637.7 
Prediction :
  [[-1.96523225]
 [-3.25005293]
 [-2.77203512]
 [-4.03644705]
 [-1.61443841]]
10 cost :  1.71877 
Prediction :
  [[ 152.86676025]
 [ 182.85481262]
 [ 180.59591675]
 [ 195.64720154]
 [ 140.33831787]]
20 cost :  1.43138 
Prediction :
  [[ 153.33079529]
 [ 183.4209137 ]
 [ 181.14933777]
 [ 196.25045776]
 [ 140.77171326]]
30 cost :  1.4245 
Prediction :
  [[ 153.32781982]
 [ 183.42565918]
 [ 181.14968872]
 [ 196.25138855]
 [ 140.77694702]]
40 cost :  1.41766 
Prediction :
  [[ 153.32341003]
 [ 183.4286499 ]
 [ 181.14833069]
 [ 196.25047302]
 [ 140.78083801]]
50 cost :  1.41083 
Prediction :
  [[ 153.31900024]
 [ 183.43165588]
 [ 181.14694214]
 [ 196.24954224]
 [ 140.78471375]]
60 cost :  1.40406 
Prediction :
  [[ 153.31462097]
 [ 183.43464661]
 [ 181.14559937]
 [ 196.24864197]
 [ 140.78858948]]
70 cost :  1.39732 
Prediction :
  [[ 153.31025696]
 [ 183.43763733]
 [ 181.14425659]
 [ 196.24772644]
 [ 140.79244995]]
80 cost :  1.39062 
Prediction :
  [[ 153.30

  [[ 152.9997406 ]
 [ 183.6499939 ]
 [ 181.0484314 ]
 [ 196.18363953]
 [ 141.06674194]]
870 cost :  0.960812 
Prediction :
  [[ 152.99621582]
 [ 183.65238953]
 [ 181.04733276]
 [ 196.1829071 ]
 [ 141.06983948]]
880 cost :  0.956462 
Prediction :
  [[ 152.9927063 ]
 [ 183.65480042]
 [ 181.04624939]
 [ 196.1822052 ]
 [ 141.07293701]]
890 cost :  0.952137 
Prediction :
  [[ 152.98919678]
 [ 183.65718079]
 [ 181.04515076]
 [ 196.18147278]
 [ 141.07601929]]
900 cost :  0.947836 
Prediction :
  [[ 152.98571777]
 [ 183.65959167]
 [ 181.0440979 ]
 [ 196.18077087]
 [ 141.07911682]]
910 cost :  0.943553 
Prediction :
  [[ 152.98222351]
 [ 183.66197205]
 [ 181.04301453]
 [ 196.18005371]
 [ 141.08218384]]
920 cost :  0.939295 
Prediction :
  [[ 152.97874451]
 [ 183.66435242]
 [ 181.04194641]
 [ 196.17933655]
 [ 141.08525085]]
930 cost :  0.93507 
Prediction :
  [[ 152.97528076]
 [ 183.66670227]
 [ 181.04084778]
 [ 196.17863464]
 [ 141.08828735]]
940 cost :  0.930859 
Prediction :
  [[ 152.97183228

1800 cost :  0.642121 
Prediction :
  [[ 152.70671082]
 [ 183.8502655 ]
 [ 180.95783997]
 [ 196.12420654]
 [ 141.32443237]]
1810 cost :  0.639478 
Prediction :
  [[ 152.70396423]
 [ 183.85214233]
 [ 180.95697021]
 [ 196.12367249]
 [ 141.326828  ]]
1820 cost :  0.636867 
Prediction :
  [[ 152.70121765]
 [ 183.85398865]
 [ 180.95613098]
 [ 196.12312317]
 [ 141.32922363]]
1830 cost :  0.634258 
Prediction :
  [[ 152.69850159]
 [ 183.85586548]
 [ 180.95529175]
 [ 196.12257385]
 [ 141.33161926]]
1840 cost :  0.631678 
Prediction :
  [[ 152.69580078]
 [ 183.85771179]
 [ 180.95445251]
 [ 196.12203979]
 [ 141.33399963]]
1850 cost :  0.629098 
Prediction :
  [[ 152.69308472]
 [ 183.85955811]
 [ 180.95359802]
 [ 196.12147522]
 [ 141.33636475]]
1860 cost :  0.626543 
Prediction :
  [[ 152.69038391]
 [ 183.86140442]
 [ 180.95277405]
 [ 196.12095642]
 [ 141.33872986]]
1870 cost :  0.623998 
Prediction :
  [[ 152.68769836]
 [ 183.86325073]
 [ 180.95195007]
 [ 196.1204071 ]
 [ 141.34109497]]
1880 cos

# Tensorflow로 데이터 불러오기

In [7]:
import numpy as np

xy = np.loadtxt('./data-01-test-score.csv', delimiter = ',', dtype=np.float32)
x_data = xy[: ,0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)
with tf.device('/cpu:0'):
    X = tf.placeholder(tf.float32, shape = [None, 3])
    Y = tf.placeholder(tf.float32, shape = [None, 1])
    W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
    b = tf.Variable(tf.random_normal([1]), name = 'bias')

    hypothesis = tf.matmul(X, W) + b
    cost = tf.reduce_mean(tf.square(hypothesis - Y))

    optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
    train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X:x_data, Y:y_data})
    if step % 10 == 0:
        print(step, "cost : ", cost_val, "\nPrediction : \n", hy_val)
#ask my score
print("your score will be ", sess.run(hypothesis, feed_dict = {X:[[100, 70, 101]]}))
print("Other score will be ", sess.run(hypothesis, feed_dict = {X:[[60, 70, 110], [90, 100, 80]]}))

(25, 3) [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]
 [  69.   74.   77.]
 [  47.   56.   60.]
 [  87.   79.   90.]
 [  79.   70.   88.]
 [  69.   70.   73.]
 [  70.   65.   74.]
 [  93.   95.   91.]
 [  79.   80.   73.]
 [  70.   73.   78.]
 [  93.   89.   96.]
 [  78.   75.   68.]
 [  81.   90.   93.]
 [  88.   92.   86.]
 [  78.   83.   77.]
 [  82.   86.   90.]
 [  86.   82.   89.]
 [  78.   83.   85.]
 [  76.   83.   71.]
 [  96.   93.   95.]] 25
(25, 1) [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]
 [ 149.]
 [ 115.]
 [ 175.]
 [ 164.]
 [ 141.]
 [ 141.]
 [ 184.]
 [ 152.]
 [ 148.]
 [ 192.]
 [ 147.]
 [ 183.]
 [ 177.]
 [ 159.]
 [ 177.]
 [ 175.]
 [ 175.]
 [ 149.]
 [ 192.]]
0 cost :  76783.4 
Prediction : 
 [[-104.35324097]
 [-128.66474915]
 [-124.88755798]
 [-137.2130127 ]
 [ -98.20556641]
 [ -75.15570831]
 [-103.98744202]
 [ -78.66026306]
 [-122.73751831]
 [-116.98429108]
 [ -99.92588043]
 [-100.5

450 cost :  22.2668 
Prediction : 
 [[ 155.4445343 ]
 [ 184.59210205]
 [ 183.21565247]
 [ 198.77987671]
 [ 140.58604431]
 [ 101.69981384]
 [ 147.89538574]
 [ 108.57244873]
 [ 170.8000946 ]
 [ 155.97669983]
 [ 142.59225464]
 [ 139.15301514]
 [ 190.17012024]
 [ 158.95004272]
 [ 148.11373901]
 [ 186.7406311 ]
 [ 151.59977722]
 [ 177.76437378]
 [ 181.76315308]
 [ 162.61738586]
 [ 173.5940094 ]
 [ 172.41053772]
 [ 165.90840149]
 [ 158.70635986]
 [ 192.15097046]]
460 cost :  22.1301 
Prediction : 
 [[ 155.43080139]
 [ 184.59536743]
 [ 183.20796204]
 [ 198.78045654]
 [ 140.58605957]
 [ 101.71598816]
 [ 147.90359497]
 [ 108.5888443 ]
 [ 170.81871033]
 [ 156.01554871]
 [ 142.59687805]
 [ 139.16972351]
 [ 190.15333557]
 [ 158.92457581]
 [ 148.12594604]
 [ 186.75068665]
 [ 151.57078552]
 [ 177.77531433]
 [ 181.74267578]
 [ 162.59854126]
 [ 173.60328674]
 [ 172.42111206]
 [ 165.91304016]
 [ 158.671875  ]
 [ 192.14704895]]
470 cost :  21.9945 
Prediction : 
 [[ 155.41714478]
 [ 184.59863281]
 [ 183

910 cost :  17.0475 
Prediction : 
 [[ 154.87736511]
 [ 184.72302246]
 [ 182.89508057]
 [ 198.80648804]
 [ 140.57783508]
 [ 102.36853027]
 [ 148.24613953]
 [ 109.27096558]
 [ 171.57009888]
 [ 157.59321594]
 [ 142.78651428]
 [ 139.847229  ]
 [ 189.4682312 ]
 [ 157.88354492]
 [ 148.6290741 ]
 [ 187.15663147]
 [ 150.37986755]
 [ 178.23439026]
 [ 180.90907288]
 [ 161.83346558]
 [ 173.98825073]
 [ 172.8482666 ]
 [ 166.10826111]
 [ 157.26907349]
 [ 191.98194885]]
920 cost :  16.9554 
Prediction : 
 [[ 154.8664093 ]
 [ 184.72546387]
 [ 182.8888092 ]
 [ 198.80705261]
 [ 140.57746887]
 [ 102.38147736]
 [ 148.25317383]
 [ 109.28495026]
 [ 171.58502197]
 [ 157.62477112]
 [ 142.7903595 ]
 [ 139.86073303]
 [ 189.45448303]
 [ 157.8625946 ]
 [ 148.63929749]
 [ 187.16470337]
 [ 150.35577393]
 [ 178.24389648]
 [ 180.89237976]
 [ 161.81817627]
 [ 173.99612427]
 [ 172.85676575]
 [ 166.11231995]
 [ 157.24099731]
 [ 191.97853088]]
930 cost :  16.864 
Prediction : 
 [[ 154.85546875]
 [ 184.7278595 ]
 [ 182.

1360 cost :  13.5884 
Prediction : 
 [[ 154.43336487]
 [ 184.81658936]
 [ 182.6391449 ]
 [ 198.83131409]
 [ 140.55458069]
 [ 102.89307404]
 [ 148.54020691]
 [ 109.85555267]
 [ 172.17393494]
 [ 158.87962341]
 [ 142.94502258]
 [ 140.39668274]
 [ 188.90379333]
 [ 157.02212524]
 [ 149.05177307]
 [ 187.48303223]
 [ 149.38540649]
 [ 178.63375854]
 [ 180.22612   ]
 [ 161.20960999]
 [ 174.31512451]
 [ 173.19232178]
 [ 166.28015137]
 [ 156.12123108]
 [ 191.83732605]]
1370 cost :  13.5256 
Prediction : 
 [[ 154.42457581]
 [ 184.81834412]
 [ 182.63401794]
 [ 198.83184814]
 [ 140.55392456]
 [ 102.90345001]
 [ 148.54624939]
 [ 109.86754608]
 [ 172.18589783]
 [ 158.90533447]
 [ 142.94822693]
 [ 140.40762329]
 [ 188.89245605]
 [ 157.004776  ]
 [ 149.06036377]
 [ 187.48950195]
 [ 149.36526489]
 [ 178.64202881]
 [ 180.2124176 ]
 [ 161.19714355]
 [ 174.32180786]
 [ 173.19915771]
 [ 166.28373718]
 [ 156.09823608]
 [ 191.83430481]]
1380 cost :  13.4633 
Prediction : 
 [[ 154.41583252]
 [ 184.82008362]
 [ 

1840 cost :  11.1003 
Prediction : 
 [[ 154.05702209]
 [ 184.88708496]
 [ 182.41732788]
 [ 198.85630798]
 [ 140.51824951]
 [ 103.33869934]
 [ 148.80870056]
 [ 110.38835144]
 [ 172.68681335]
 [ 159.99072266]
 [ 143.08572388]
 [ 140.86833191]
 [ 188.41062927]
 [ 156.26577759]
 [ 149.42910767]
 [ 187.76042175]
 [ 148.503479  ]
 [ 179.00331116]
 [ 179.63302612]
 [ 160.67074585]
 [ 174.61018372]
 [ 173.48530579]
 [ 166.44111633]
 [ 155.12586975]
 [ 191.70259094]]
1850 cost :  11.0584 
Prediction : 
 [[ 154.05012512]
 [ 184.88827515]
 [ 182.41317749]
 [ 198.85682678]
 [ 140.51741028]
 [ 103.34690857]
 [ 148.81385803]
 [ 110.39855957]
 [ 172.69624329]
 [ 160.01138306]
 [ 143.08837891]
 [ 140.87705994]
 [ 188.40141296]
 [ 156.25157166]
 [ 149.43626404]
 [ 187.76553345]
 [ 148.48683167]
 [ 179.01045227]
 [ 179.6219635 ]
 [ 160.66073608]
 [ 174.61579895]
 [ 173.4907074 ]
 [ 166.44425964]
 [ 155.10731506]
 [ 191.69998169]]
1860 cost :  11.0169 
Prediction : 
 [[ 154.04322815]
 [ 184.88948059]
 [ 

## Queue Runners

너무 커다란 데이터라면 메모리가 부족할수 있는데 tensorflow에서는 Queue Runners를 통해 일부데이터를 순차적으로 사용함으로써 큰 데이터도 메모리를 절약하며 읽을 수 있다. 


In [9]:
#첫번째 argument의 배열에는 데이터를 하나 뿐만 아니라 여러개 더 넣을 수 있다. 
filename_queue = tf.train.string_input_producer(['./data-01-test-score.csv'], shuffle=False, name="filename_queue")
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)
with tf.device('/cpu:0'):
    train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

    X = tf.placeholder(tf.float32, shape=[None, 3])
    Y = tf.placeholder(tf.float32, shape=[None, 1])

    W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
    b = tf.Variable(tf.random_normal([1]), name = 'bias')

    hypothesis = tf.matmul(X, W) + b
    cost = tf.reduce_mean(tf.square(hypothesis - Y))

    optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
    train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

#start Populating the filename queue.
coord = tf.train.Coordinator()
threads =tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
                            
coord.request_stop()
coord.join(threads)

print("your score will be ", sess.run(hypothesis, feed_dict = {X:[[100, 70, 101]]}))
print("Other score will be ", sess.run(hypothesis, feed_dict = {X:[[60, 70, 110], [90, 100, 80]]}))

0 Cost:  8964.85 
Prediction:
 [[ 59.64928055]
 [ 73.62824249]
 [ 71.42369843]
 [ 79.01391602]
 [ 55.67720413]
 [ 43.28087234]
 [ 60.51415253]
 [ 46.69290924]
 [ 70.81839752]
 [ 68.55872345]]
10 Cost:  3.8374 
Prediction:
 [[ 152.20703125]
 [ 184.88768005]
 [ 181.04214478]
 [ 198.40019226]
 [ 140.53117371]
 [ 105.8471756 ]
 [ 149.88031006]
 [ 112.94503021]
 [ 174.80563354]
 [ 164.8850708 ]]
20 Cost:  5.04853 
Prediction:
 [[ 152.83366394]
 [ 185.63664246]
 [ 181.78230286]
 [ 199.20610046]
 [ 141.10145569]
 [ 106.26687622]
 [ 150.48448181]
 [ 113.39433289]
 [ 175.50440979]
 [ 165.53155518]]
30 Cost:  5.05592 
Prediction:
 [[ 152.83992004]
 [ 185.63986206]
 [ 181.78770447]
 [ 199.21179199]
 [ 141.10299683]
 [ 106.26719666]
 [ 150.4896698 ]
 [ 113.39958954]
 [ 175.50619507]
 [ 165.53237915]]
40 Cost:  5.05241 
Prediction:
 [[ 152.84197998]
 [ 185.63804626]
 [ 181.78814697]
 [ 199.21208191]
 [ 141.10070801]
 [ 106.26470184]
 [ 150.49079895]
 [ 113.40184784]
 [ 175.50325012]
 [ 165.52886963

440 Cost:  4.92683 
Prediction:
 [[ 152.91789246]
 [ 185.56898499]
 [ 181.80329895]
 [ 199.22221375]
 [ 141.01330566]
 [ 106.17141724]
 [ 150.53367615]
 [ 113.48777771]
 [ 175.39361572]
 [ 165.39871216]]
450 Cost:  4.9241 
Prediction:
 [[ 152.91964722]
 [ 185.56738281]
 [ 181.8036499 ]
 [ 199.22247314]
 [ 141.01126099]
 [ 106.16926575]
 [ 150.53471375]
 [ 113.48985291]
 [ 175.39108276]
 [ 165.39573669]]
460 Cost:  4.92136 
Prediction:
 [[ 152.92140198]
 [ 185.56576538]
 [ 181.8039856 ]
 [ 199.22270203]
 [ 141.00920105]
 [ 106.16710663]
 [ 150.53575134]
 [ 113.49189758]
 [ 175.38853455]
 [ 165.39276123]]
470 Cost:  4.91864 
Prediction:
 [[ 152.92314148]
 [ 185.56416321]
 [ 181.80432129]
 [ 199.22294617]
 [ 141.00715637]
 [ 106.16496277]
 [ 150.53675842]
 [ 113.49396515]
 [ 175.3860321 ]
 [ 165.38981628]]
480 Cost:  4.91593 
Prediction:
 [[ 152.92489624]
 [ 185.56256104]
 [ 181.80465698]
 [ 199.22317505]
 [ 141.00511169]
 [ 106.16281891]
 [ 150.53778076]
 [ 113.49600983]
 [ 175.3835144 ]

880 Cost:  4.8209 
Prediction:
 [[ 152.98980713]
 [ 185.50236511]
 [ 181.81698608]
 [ 199.23249817]
 [ 140.92810059]
 [ 106.08325958]
 [ 150.57722473]
 [ 113.5747757 ]
 [ 175.29003906]
 [ 165.27864075]]
890 Cost:  4.81883 
Prediction:
 [[ 152.99133301]
 [ 185.50097656]
 [ 181.817276  ]
 [ 199.23272705]
 [ 140.92630005]
 [ 106.08141327]
 [ 150.57815552]
 [ 113.57666016]
 [ 175.28787231]
 [ 165.27616882]]
900 Cost:  4.81673 
Prediction:
 [[ 152.99281311]
 [ 185.49954224]
 [ 181.8175354 ]
 [ 199.23294067]
 [ 140.92446899]
 [ 106.07956696]
 [ 150.57910156]
 [ 113.57854462]
 [ 175.28569031]
 [ 165.27368164]]
910 Cost:  4.8147 
Prediction:
 [[ 152.99432373]
 [ 185.49815369]
 [ 181.81782532]
 [ 199.23316956]
 [ 140.92266846]
 [ 106.07774353]
 [ 150.58004761]
 [ 113.58042908]
 [ 175.28355408]
 [ 165.27124023]]
920 Cost:  4.81265 
Prediction:
 [[ 152.99581909]
 [ 185.49676514]
 [ 181.81809998]
 [ 199.23338318]
 [ 140.92086792]
 [ 106.07591248]
 [ 150.58099365]
 [ 113.58230591]
 [ 175.28140259]


1340 Cost:  4.73743 
Prediction:
 [[ 153.05401611]
 [ 185.44174194]
 [ 181.8285675 ]
 [ 199.24234009]
 [ 140.84973145]
 [ 106.00475311]
 [ 150.61886597]
 [ 113.65775299]
 [ 175.19784546]
 [ 165.17456055]]
1350 Cost:  4.73587 
Prediction:
 [[ 153.05531311]
 [ 185.44052124]
 [ 181.82879639]
 [ 199.24253845]
 [ 140.84812927]
 [ 106.00318146]
 [ 150.61973572]
 [ 113.6594696 ]
 [ 175.19599915]
 [ 165.17253113]]
1360 Cost:  4.73432 
Prediction:
 [[ 153.05657959]
 [ 185.43930054]
 [ 181.82902527]
 [ 199.24273682]
 [ 140.8465271 ]
 [ 106.00161743]
 [ 150.62060547]
 [ 113.66117859]
 [ 175.19415283]
 [ 165.17047119]]
1370 Cost:  4.73277 
Prediction:
 [[ 153.05787659]
 [ 185.43807983]
 [ 181.82923889]
 [ 199.24293518]
 [ 140.84495544]
 [ 106.00005341]
 [ 150.62145996]
 [ 113.66288757]
 [ 175.19233704]
 [ 165.16844177]]
1380 Cost:  4.7312 
Prediction:
 [[ 153.05911255]
 [ 185.43684387]
 [ 181.82945251]
 [ 199.24311829]
 [ 140.84336853]
 [ 105.99849701]
 [ 150.62229919]
 [ 113.66458893]
 [ 175.1904

1770 Cost:  4.67839 
Prediction:
 [[ 153.10546875]
 [ 185.39227295]
 [ 181.83734131]
 [ 199.25073242]
 [ 140.78509521]
 [ 105.94199371]
 [ 150.65444946]
 [ 113.72841644]
 [ 175.12420654]
 [ 165.09362793]]
1780 Cost:  4.67719 
Prediction:
 [[ 153.10656738]
 [ 185.39117432]
 [ 181.83752441]
 [ 199.25091553]
 [ 140.78369141]
 [ 105.94065094]
 [ 150.65522766]
 [ 113.72999573]
 [ 175.12261963]
 [ 165.09191895]]
1790 Cost:  4.67602 
Prediction:
 [[ 153.10768127]
 [ 185.3901062 ]
 [ 181.83772278]
 [ 199.25111389]
 [ 140.78227234]
 [ 105.93930054]
 [ 150.65602112]
 [ 113.73155212]
 [ 175.12103271]
 [ 165.09020996]]
1800 Cost:  4.67486 
Prediction:
 [[ 153.10877991]
 [ 185.38905334]
 [ 181.83790588]
 [ 199.25131226]
 [ 140.78088379]
 [ 105.93796539]
 [ 150.65681458]
 [ 113.73312378]
 [ 175.11947632]
 [ 165.08851624]]
1810 Cost:  4.67367 
Prediction:
 [[ 153.10987854]
 [ 185.38798523]
 [ 181.83808899]
 [ 199.2514801 ]
 [ 140.77947998]
 [ 105.93662262]
 [ 150.65760803]
 [ 113.73468018]
 [ 175.117