# Tensorflow manipulation

In [12]:
import tensorflow as tf
import numpy as np
import matplotlib as plt
import pprint

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [8]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
#rank
print(t.ndim)
#shape
print(t.shape)
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

[ 0.  1.  2.  3.  4.  5.  6.]
1
(7,)
0.0 1.0 6.0
[ 2.  3.  4.] [ 4.  5.]
[ 0.  1.] [ 3.  4.  5.  6.]


In [13]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim)
print(t.shape)

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


In [14]:
t = tf.constant([1, 2, 3, 4])
tf.shape(t).eval()

array([4])

In [15]:
t = tf.constant([[1,2],[3,4]])
tf.shape(t).eval()

array([2, 2])

In [17]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
print(t.eval())
tf.shape(t).eval()

[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]]


array([1, 2, 3, 4])

- axis의 개념 
shape = (1, 2, 3, 4)

rank = 4

[<- axis = 0
    [<-- axis = 1
        [<-- axis = 2
            [1, 2, 3, 4],--> axis = 3
            [5, 6, 7, 8],
            [9, 10, 11, 12]
         ],
         [
             [13, 14, 15, 16],
             [17, 18, 19, 20],
             [21, 22, 23, 24]
         ],
     ]
]

axis = -1 의 경우 가장 안쪽에 있는것 여기서는 3
        


In [20]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.],[2.]])

print("matrix 1 shape : {}".format(matrix1.shape))
print("matrix 2 shape : {}".format(matrix2.shape))
tf.matmul(matrix1, matrix2).eval()

matrix 1 shape : (2, 2)
matrix 2 shape : (2, 1)


array([[  5.],
       [ 11.]], dtype=float32)

- matmul과 아래와는 다르다. (boradcasting이라고 한다. 같은 행,렬끼리 연산하는것 
- 근데 shape가 달라도 연산함 (조심해서 사용할것)

In [19]:

(matrix1*matrix2).eval()

array([[ 1.,  2.],
       [ 6.,  8.]], dtype=float32)

- reduce_mean
- 차원축소의 개념이 들어있기때문에 reduce


In [31]:
tf.reduce_mean([1, 2], axis=0).eval()

1

In [24]:
x =[[1., 2], 
   [3., 4.]]

tf.reduce_mean(x).eval()

2.5

In [26]:
# axis = 0 은 열들의 차원이다
# 따라서 1열과 2열의 평균을 낸다.
tf.reduce_mean(x, axis = 0).eval()

array([ 2.,  3.], dtype=float32)

In [27]:
#axis =1 (=-1)은 각 행의 차원이다.
#따라서 각 행들의 평균을 낸다.
#result = [tf.reduce_mean([1., 2.]), tf.reduce_mean([3., 4.])]
tf.reduce_mean(x, axis = 1).eval()

array([ 1.5,  3.5], dtype=float32)

In [28]:
tf.reduce_mean(x, axis = -1).eval()

array([ 1.5,  3.5], dtype=float32)

- reduce_sum
- reduce_mean과 유사

In [32]:
tf.reduce_sum(x).eval()

10.0

In [33]:
tf.reduce_sum(x, axis = 0).eval()

array([ 4.,  6.], dtype=float32)

In [34]:
tf.reduce_sum(x, axis = 1).eval()

array([ 3.,  7.], dtype=float32)

In [35]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

- Argmax 함수

아래 예제에서 axis = 0이므로
[
    [0, 1, 2],
    [2, 1, 0]
]
에서 가장 바깥쪽의 축에서 연산을 하게 된다.
[0, 1, 2]와 [2, 1, 0]에서 같은 인덱스끼리 오른쪽이 크면 1 왼쪽이 크면 0으로 연산한다.
따라서 결과는 [1, 0, 0]이 된다.

In [39]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis = 0).eval()

array([1, 0, 0], dtype=int64)

아래 예제에서 axis = 1이므로
[
    [0, 1, 2],
    [2, 1, 0]
]
에서 안쪽의 축에서 연산을 하게 된다. 
따라서 [argmax([0, 1, 2]), argmax([2, 1, 0])]와 같으므로
[2. 0]이된다

In [37]:
tf.argmax(x, axis = 1).eval()

array([2, 0], dtype=int64)

In [38]:
tf.argmax(x, axis = -1).eval()

array([2, 0], dtype=int64)

### reshape


In [43]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
             
              [[6, 7, 8],
               [9, 10, 11]]])
print(t)
t.shape

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


(2, 2, 3)

In [48]:
#shape = (4,3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [49]:
#shape = (4, 1, 3)
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [50]:
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2])

In [54]:
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]])

# one_hot encoding
- 3개의 클래스일때 0~2까지의 값을 각각의 인덱스에 맞는 1이 하나 있는 binary 벡터로 바꾸어준다.
- 자동적으로 expand_dims가 이루어지기때문에 아래 랭크가 2인것이 바꾸고 나면 rank가 3이된다 (4, 1, 3) 따라서 reshape를 통해 다시 (4, 3)으로 바꿔줄 필요가 있다.

In [58]:

tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

In [59]:
#위가 
t = tf.one_hot([[0], [1], [2], [0]], depth= 3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

# casting

In [60]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [61]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0])

# stack

In [64]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

#pack along first dim
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [69]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

# ones and zeros like

In [70]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [71]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

# zip

In [72]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [75]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
