In [2]:
import tensorflow as tf

In [3]:
#tensorflow 안에서 grdient를 손대고 싶을 떄 사용하는 방법
X = [1, 2, 3]
Y = [1, 2, 3]

W = tf.Variable(5.)
hypothesis = X * W

#직접 구한 gradient값
gradient = tf.reduce_mean((W * X - Y) * X) * 2

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.01)

#Gradient값을 얻는다.
gvs = optimizer.compute_gradients(cost,[W])

#Gradient 적용
apply_gradient = optimizer.apply_gradients(gvs)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(100):
    print(step, sess.run([gradient,  gvs]))
    sess.run(apply_gradient)

0 [37.333332, [(37.333336, 5.0)]]
1 [33.848888, [(33.848888, 4.6266665)]]
2 [30.689657, [(30.689657, 4.2881775)]]
3 [27.825287, [(27.825287, 3.9812808)]]
4 [25.228262, [(25.228264, 3.703028)]]
5 [22.873621, [(22.873623, 3.4507453)]]
6 [20.738752, [(20.738752, 3.2220092)]]
7 [18.803137, [(18.803137, 3.0146217)]]
8 [17.048176, [(17.048176, 2.8265903)]]
9 [15.457013, [(15.457014, 2.6561086)]]
10 [14.014359, [(14.01436, 2.5015385)]]
11 [12.706352, [(12.706352, 2.3613949)]]
12 [11.520427, [(11.520427, 2.2343314)]]
13 [10.445186, [(10.445186, 2.119127)]]
14 [9.4703016, [(9.4703016, 2.0146751)]]
15 [8.5864067, [(8.5864067, 1.9199722)]]
16 [7.7850089, [(7.7850089, 1.8341081)]]
17 [7.0584083, [(7.0584083, 1.756258)]]
18 [6.3996239, [(6.3996239, 1.685674)]]
19 [5.8023257, [(5.8023257, 1.6216778)]]
20 [5.260776, [(5.260776, 1.5636545)]]
21 [4.7697697, [(4.7697697, 1.5110468)]]
22 [4.3245912, [(4.3245912, 1.4633491)]]
23 [3.9209633, [(3.9209635, 1.4201032)]]
24 [3.5550067, [(3.5550067, 1.3808936)]

# Multi-variable linear regression
- hypothesis : H(X1,X2,X3....) = W1X1 + W2X2 + ...  WnXn
- cost : 


In [4]:
#5개의 샘플 데이터 
x1_data = [73, 93, 89, 96, 73]
x2_data = [80, 88, 91, 98, 66]
x3_data = [75, 93, 90, 100, 70]
y_data = [152, 185, 180, 196, 142]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = x1 * w1 + x2 * w2 + x3 + w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    if step % 10 == 0:
        print(step, "cost : ", cost_val, "\nprediction\n", hy_val)

0 cost :  38686.7 
prediction
 [-20.93388939 -26.91327477 -25.79434013 -24.80520439 -23.8736248 ]
10 cost :  52.6854 
prediction
 [ 149.76501465  175.04946899  175.03720093  191.6448822   131.23791504]
20 cost :  12.9264 
prediction
 [ 155.22459412  181.53172302  181.47119141  198.57951355  136.22186279]
30 cost :  12.8233 
prediction
 [ 155.38757324  181.74795532  181.67391968  198.79826355  136.39352417]
40 cost :  12.7612 
prediction
 [ 155.3807373   181.76324463  181.67684937  198.80169678  136.41085815]
50 cost :  12.6994 
prediction
 [ 155.36853027  181.77212524  181.6734314   198.79827881  136.42324829]
60 cost :  12.638 
prediction
 [ 155.3561554   181.78074646  181.6697998   198.7946167   136.43540955]
70 cost :  12.577 
prediction
 [ 155.34384155  181.78936768  181.66618347  198.79100037  136.4475708 ]
80 cost :  12.5162 
prediction
 [ 155.33154297  181.79794312  181.66255188  198.78735352  136.45968628]
90 cost :  12.4557 
prediction
 [ 155.3192749   181.80651855  181.658966

800 cost :  8.88107 
prediction
 [ 154.52558899  182.36027527  181.42553711  198.54925537  137.25366211]
810 cost :  8.83959 
prediction
 [ 154.51545715  182.36740112  181.4225769   198.54629517  137.26370239]
820 cost :  8.79833 
prediction
 [ 154.50531006  182.37445068  181.41958618  198.54327393  137.27368164]
830 cost :  8.75735 
prediction
 [ 154.49520874  182.38148499  181.41659546  198.5402832   137.28361511]
840 cost :  8.71652 
prediction
 [ 154.4851532   182.3885498   181.41366577  198.53733826  137.2935791 ]
850 cost :  8.67594 
prediction
 [ 154.4750824   182.39553833  181.41070557  198.53434753  137.3034668 ]
860 cost :  8.63558 
prediction
 [ 154.46505737  182.40252686  181.40774536  198.53137207  137.31332397]
870 cost :  8.59542 
prediction
 [ 154.45506287  182.40950012  181.40481567  198.52842712  137.32318115]
880 cost :  8.55544 
prediction
 [ 154.44508362  182.41647339  181.40188599  198.52548218  137.33300781]
890 cost :  8.51568 
prediction
 [ 154.43511963  182.42

1600 cost :  6.16493 
prediction
 [ 153.79165649  182.87245178  181.20968628  198.33236694  137.97695923]
1610 cost :  6.13766 
prediction
 [ 153.78341675  182.87818909  181.20726013  198.32992554  137.9850769 ]
1620 cost :  6.11053 
prediction
 [ 153.775177    182.88391113  181.20483398  198.32748413  137.99316406]
1630 cost :  6.08358 
prediction
 [ 153.76699829  182.88961792  181.2024231   198.32507324  138.00123596]
1640 cost :  6.05674 
prediction
 [ 153.75881958  182.89532471  181.20001221  198.32264709  138.00927734]
1650 cost :  6.03004 
prediction
 [ 153.75067139  182.90100098  181.19760132  198.32022095  138.01730347]
1660 cost :  6.00348 
prediction
 [ 153.74253845  182.90667725  181.19522095  198.31784058  138.02532959]
1670 cost :  5.97707 
prediction
 [ 153.73446655  182.91235352  181.19287109  198.31546021  138.03334045]
1680 cost :  5.95077 
prediction
 [ 153.72636414  182.91799927  181.19047546  198.31304932  138.04129028]
1690 cost :  5.92461 
prediction
 [ 153.718292

# Multi-Variables linear regression by Matrix

In [5]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]
#Placeholder for tensor that will be always fed
#None은 원하는 어떠한 값이든 넣을 수 있다는 뜻 
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1], name = 'weight'))
b = tf.Variable(tf.random_normal([1]), name = 'bias')
#hypothesis and cost
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

#minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

#Launch the graph in a Session
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X : x_data, Y : y_data})
    if step % 10 == 0:
        print(step, "cost : ", cost_val, "\nPrediction :\n ", hy_val)

0 cost :  2734.61 
Prediction :
  [[ 101.55747223]
 [ 131.22044373]
 [ 124.39283752]
 [ 136.99839783]
 [ 101.21975708]]
10 cost :  4.90548 
Prediction :
  [[ 147.78369141]
 [ 186.76585388]
 [ 179.13053894]
 [ 196.60508728]
 [ 143.58424377]]
20 cost :  4.85839 
Prediction :
  [[ 147.93153381]
 [ 186.92851257]
 [ 179.29866028]
 [ 196.78686523]
 [ 143.70567322]]
30 cost :  4.83641 
Prediction :
  [[ 147.93991089]
 [ 186.92359924]
 [ 179.30163574]
 [ 196.7888031 ]
 [ 143.69927979]]
40 cost :  4.8145 
Prediction :
  [[ 147.94786072]
 [ 186.91818237]
 [ 179.30412292]
 [ 196.79019165]
 [ 143.69250488]]
50 cost :  4.79276 
Prediction :
  [[ 147.95578003]
 [ 186.91281128]
 [ 179.30661011]
 [ 196.79159546]
 [ 143.68577576]]
60 cost :  4.77114 
Prediction :
  [[ 147.96366882]
 [ 186.90742493]
 [ 179.30908203]
 [ 196.79298401]
 [ 143.67906189]]
70 cost :  4.74959 
Prediction :
  [[ 147.97155762]
 [ 186.90206909]
 [ 179.31155396]
 [ 196.79437256]
 [ 143.67234802]]
80 cost :  4.72817 
Prediction :
 

680 cost :  3.63168 
Prediction :
  [[ 148.41481018]
 [ 186.60063171]
 [ 179.45045471]
 [ 196.87077332]
 [ 143.2971344 ]]
690 cost :  3.61621 
Prediction :
  [[ 148.42149353]
 [ 186.59608459]
 [ 179.45254517]
 [ 196.87188721]
 [ 143.29150391]]
700 cost :  3.60082 
Prediction :
  [[ 148.42816162]
 [ 186.59155273]
 [ 179.45463562]
 [ 196.87301636]
 [ 143.28587341]]
710 cost :  3.58553 
Prediction :
  [[ 148.43481445]
 [ 186.58703613]
 [ 179.45674133]
 [ 196.87414551]
 [ 143.2802887 ]]
720 cost :  3.5703 
Prediction :
  [[ 148.44143677]
 [ 186.58251953]
 [ 179.45880127]
 [ 196.87524414]
 [ 143.27468872]]
730 cost :  3.55514 
Prediction :
  [[ 148.44807434]
 [ 186.57803345]
 [ 179.46090698]
 [ 196.87637329]
 [ 143.26913452]]
740 cost :  3.54007 
Prediction :
  [[ 148.45466614]
 [ 186.5735321 ]
 [ 179.46296692]
 [ 196.87747192]
 [ 143.26356506]]
750 cost :  3.52511 
Prediction :
  [[ 148.46124268]
 [ 186.56907654]
 [ 179.46504211]
 [ 196.87858582]
 [ 143.25804138]]
760 cost :  3.5102 
Predi

1390 cost :  2.71395 
Prediction :
  [[ 148.84831238]
 [ 186.3062439 ]
 [ 179.58680725]
 [ 196.94181824]
 [ 142.93412781]]
1400 cost :  2.70333 
Prediction :
  [[ 148.85385132]
 [ 186.30249023]
 [ 179.58857727]
 [ 196.94270325]
 [ 142.92950439]]
1410 cost :  2.69277 
Prediction :
  [[ 148.859375  ]
 [ 186.29872131]
 [ 179.59031677]
 [ 196.943573  ]
 [ 142.9249115 ]]
1420 cost :  2.68225 
Prediction :
  [[ 148.86489868]
 [ 186.29498291]
 [ 179.59207153]
 [ 196.94445801]
 [ 142.9203186 ]]
1430 cost :  2.67181 
Prediction :
  [[ 148.87039185]
 [ 186.29124451]
 [ 179.59378052]
 [ 196.94532776]
 [ 142.91575623]]
1440 cost :  2.66141 
Prediction :
  [[ 148.87588501]
 [ 186.28755188]
 [ 179.59553528]
 [ 196.94619751]
 [ 142.91120911]]
1450 cost :  2.65105 
Prediction :
  [[ 148.88136292]
 [ 186.28382874]
 [ 179.59724426]
 [ 196.94706726]
 [ 142.90664673]]
1460 cost :  2.64076 
Prediction :
  [[ 148.8868103 ]
 [ 186.28012085]
 [ 179.59896851]
 [ 196.94790649]
 [ 142.90211487]]
1470 cost :  2.6

# Tensorflow로 데이터 불러오기

In [6]:
import numpy as np

xy = np.loadtxt('Data_01_test_score.csv', delimiter = ',', dtype=np.float32)
x_data = xy[: ,0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])
W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X:x_data, Y:y_data})
    if step % 10 == 0:
        print(step, "cost : ", cost_val, "\nPrediction : \n", hy_val)
#ask my score
print("your score will be ", sess.run(hypothesis, feed_dict = {X:[[100, 70, 101]]}))
print("Other score will be ", sess.run(hypothesis, feed_dict = {X:[[60, 70, 110], [90, 100, 80]]}))

(5, 3) [[  73.   80.   75.]
 [  93.   88.   93.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]] 5
(5, 1) [[ 152.]
 [ 185.]
 [ 196.]
 [ 142.]
 [ 101.]]
0 cost :  2818.49 
Prediction : 
 [[  97.78373718]
 [ 124.42462921]
 [ 127.22466278]
 [  99.03292084]
 [  70.87576294]]
10 cost :  10.8588 
Prediction : 
 [[ 148.27806091]
 [ 185.12155151]
 [ 192.35076904]
 [ 145.32844543]
 [ 105.00389099]]
20 cost :  10.555 
Prediction : 
 [[ 148.75694275]
 [ 185.67100525]
 [ 192.95307922]
 [ 145.74276733]
 [ 105.30294037]]
30 cost :  10.4868 
Prediction : 
 [[ 148.77801514]
 [ 185.67001343]
 [ 192.96484375]
 [ 145.73722839]
 [ 105.29242706]]
40 cost :  10.4192 
Prediction : 
 [[ 148.79483032]
 [ 185.66400146]
 [ 192.97119141]
 [ 145.72787476]
 [ 105.27915192]]
50 cost :  10.352 
Prediction : 
 [[ 148.81155396]
 [ 185.6579895 ]
 [ 192.97746277]
 [ 145.71850586]
 [ 105.2658844 ]]
60 cost :  10.2853 
Prediction : 
 [[ 148.82821655]
 [ 185.65197754]
 [ 192.98371887]
 [ 145.709198  ]
 [ 105

660 cost :  7.06395 
Prediction : 
 [[ 149.72241211]
 [ 185.32899475]
 [ 193.32049561]
 [ 145.20640564]
 [ 104.54447937]]
670 cost :  7.02139 
Prediction : 
 [[ 149.73568726]
 [ 185.32417297]
 [ 193.32551575]
 [ 145.19888306]
 [ 104.53398132]]
680 cost :  6.97916 
Prediction : 
 [[ 149.74893188]
 [ 185.31939697]
 [ 193.33052063]
 [ 145.19142151]
 [ 104.52352142]]
690 cost :  6.93723 
Prediction : 
 [[ 149.76210022]
 [ 185.31462097]
 [ 193.33552551]
 [ 145.18395996]
 [ 104.5131073 ]]
700 cost :  6.8956 
Prediction : 
 [[ 149.77523804]
 [ 185.30987549]
 [ 193.34049988]
 [ 145.17652893]
 [ 104.50273132]]
710 cost :  6.8543 
Prediction : 
 [[ 149.78831482]
 [ 185.30513   ]
 [ 193.34541321]
 [ 145.16912842]
 [ 104.49237061]]
720 cost :  6.81326 
Prediction : 
 [[ 149.80136108]
 [ 185.30041504]
 [ 193.35040283]
 [ 145.16177368]
 [ 104.48207855]]
730 cost :  6.77257 
Prediction : 
 [[ 149.8143158 ]
 [ 185.29571533]
 [ 193.3553009 ]
 [ 145.15440369]
 [ 104.47181702]]
740 cost :  6.73214 
Predi

 [ 103.91403198]]
1350 cost :  4.75272 
Prediction : 
 [[ 150.53208923]
 [ 185.03521729]
 [ 193.62884521]
 [ 144.74606323]
 [ 103.90591431]]
1360 cost :  4.72707 
Prediction : 
 [[ 150.5423584 ]
 [ 185.03149414]
 [ 193.63279724]
 [ 144.74015808]
 [ 103.89785004]]
1370 cost :  4.70165 
Prediction : 
 [[ 150.55258179]
 [ 185.02775574]
 [ 193.63670349]
 [ 144.73429871]
 [ 103.8897934 ]]
1380 cost :  4.6764 
Prediction : 
 [[ 150.5627594 ]
 [ 185.02404785]
 [ 193.640625  ]
 [ 144.72845459]
 [ 103.8817749 ]]
1390 cost :  4.65133 
Prediction : 
 [[ 150.57292175]
 [ 185.02035522]
 [ 193.64451599]
 [ 144.72262573]
 [ 103.87379456]]
1400 cost :  4.62643 
Prediction : 
 [[ 150.58305359]
 [ 185.0166626 ]
 [ 193.64839172]
 [ 144.71682739]
 [ 103.86582184]]
1410 cost :  4.60171 
Prediction : 
 [[ 150.59313965]
 [ 185.01298523]
 [ 193.65228271]
 [ 144.71105957]
 [ 103.85788727]]
1420 cost :  4.57718 
Prediction : 
 [[ 150.60319519]
 [ 185.00933838]
 [ 193.65614319]
 [ 144.70529175]
 [ 103.84999847]]

## Queue Runners

너무 커다란 데이터라면 메모리가 부족할수 있는데 tensorflow에서는 Queue Runners를 통해 일부데이터를 순차적으로 사용함으로써 큰 데이터도 메모리를 절약하며 읽을 수 있다. 


In [11]:
#첫번째 argument의 배열에는 데이터를 하나 뿐만 아니라 여러개 더 넣을 수 있다. 
filename_queue = tf.train.string_input_producer(['data_01_test_score.csv'], shuffle=False, name="filename_queue")
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

#start Populating the filename queue.
coord = tf.train.Coordinator()
threads =tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
                            
coord.request_stop()
coord.join(threads)

print("your score will be ", sess.run(hypothesis, feed_dict = {X:[[100, 70, 101]]}))
print("Other score will be ", sess.run(hypothesis, feed_dict = {X:[[60, 70, 110], [90, 100, 80]]}))

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Field 0 in record 0 is not a valid float: #Exam1
	 [[Node: DecodeCSV = DecodeCSV[OUT_TYPE=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], field_delim=",", use_quote_delim=true, _device="/job:localhost/replica:0/task:0/cpu:0"](ReaderReadV2:1, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_1, DecodeCSV/record_defaults_2, DecodeCSV/record_defaults_3)]]


OutOfRangeError: FIFOQueue '_18_batch_3/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[Node: batch_3 = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch_3/fifo_queue, batch_3/n)]]

Caused by op 'batch_3', defined at:
  File "C:\Users\kjw1o\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\kjw1o\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-3b64538b7399>", line 8, in <module>
    train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\tensorflow\python\training\input.py", line 922, in batch
    name=name)
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\tensorflow\python\training\input.py", line 716, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 457, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 1342, in _queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\kjw1o\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): FIFOQueue '_18_batch_3/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[Node: batch_3 = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch_3/fifo_queue, batch_3/n)]]
